server:
    port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/user_registration
    driver-class-name: org.postgresql.Driver
    username: msbeigi
    password: password
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
